app/__init__.py
이제 x-api-key를 사용할 필요가 없습니다!
key 인증 기능 삭제했어요
테스트는 안 하긴 했는데 될 거에요
Closes #
=> 💣 remove: api-key

app/routes/mcp_server.py, app/routes/mcp_server_activation.py, app/routes/message.py, app/routes/session.py, app/routes/user.py, pyproject.toml
(라우트 API 입력/출력 모델 수정)
서버 문제 수정
- 
Closes #
=> 🔧 refactor: Align route API input/output models

app/__init__.py, app/dao/base.py, app/dao/message_dao.py, app/dao/session_dao.py, app/dao/user_dao.py, app/models/message.py, app/models/session.py, app/models/user.py, app/routes/message.py, app/routes/session.py, app/routes/user.py, app/schemas/message_schema.py, app/schemas/session_schema.py, app/schemas/user_schema.py, app/services/message_service.py, app/services/session_service.py, app/services/user_service.py, app/utils/openai_client.py, config.py, pyproject.toml
Azure OpenAI 연동과 백엔드 계층 구조를 개선함
- 백엔드 계층 구조가 변경됨
- Azure OpenAI 연동됨
Closes #
=> Azure OpenAI 연동 코드 추가 및 계층 구조 변경

.gitignore, app/services/message_service.py
프론트 쪽에 toolmessage가 넘어가지 않는 문제가 있어 해결했습니다.
- 
Closes #
=> ⚡️ improve: 프론트 랭그래프 toolmessage 추가

app/dao/message_dao.py, app/dao/session_dao.py, app/dao/user_dao.py
=> 🐛 bug: dao recursion error

app/__init__.py, app/routes/auth.py, app/routes/debug/user.py, app/routes/message.py, app/routes/session.py, app/utils/app_config.py, app/utils/auth_middleware.py, app/utils/openai_client.py
config 관리를 한 곳으로 집중합니다.
- test code에서 사용하는 config는 일반 config와 다른 부분이 있는데, route 및 utils에서는 일반 config를 직접 참조하여 사용하기 때문에 문제가 발생.
- 그래서 중앙 집중 형태로 변경함
Closes #
=> 🎨 Change config management

app/utils/app_config.py, config.py
=> 📱 fix: google client config

app/routes/auth.py, app/utils/app_config.py, app/utils/auth_middleware.py, config.py
google_web_client_id 수정
- 
Closes #
=> 🔧 fix: oauth client

.github/workflows/main_seobi-backend.yml, app/models/schedule.py, config.py
PR에서 테스트가 동작하도록 하는 기능입니다.
- 
Closes #
=> 💚 Introduce pr test

.github/workflows/main_seobi-backend.yml, app/services/session_service.py
session이 닫히지 않는 문제를 해결합니다.
- message service를 사용하여 세션에 해당하는 메시지를 읽도록 수정하였습니다.
Closes #
=> 🐛 Fix session close

app/__init__.py, app/dao/auto_task_dao.py, app/routes/debug/auto_task.py, app/schemas/auto_task_schema.py, app/services/auto_task_service.py, app/services/auto_task_sevice.py
auto task CRUD 구현, swagger 테스트 완료
- dao, service, schema, init, routes 추가
- 오타 수정
- \# NOTE 작성
- status, finish_at, in range service 코드 routes 에 작성(편의성)
- get_all_by_user_id_in_range 로 함수명 변경
Closes #
PR 후 주은님 피드백 (swagger 문서 설명 추가) 수정하겠습니다.
=> auto task CRUD 구현 성공

app/services/interest_service.py
interest service에 잘못된 참조가 있었음
- 제대로된 참조로 수정
Closes #
=> 🐛 Fix undefined reference

app/routes/session.py
유저 세션 못가져오는 문제 해결
- 불필요한 로직을 제거하여 session service의 리턴값을 그대로 리턴하도록 수정하였습니다.
Closes #
=> 🐛 유저 세션 못가져오는 문제 해결

app/__init__.py
dotenv 변수를 override하는 옵션 추가 PR
- 
Closes #
=> 🧑‍💻 Add override option for load_dotenv

.github/workflows/main_seobi-backend.yml, app/utils/app_config.py
GOOGLE CLIENT ID를 찾지 못하는 문제를 해결하는 PR입니다.
- GOOGLE WEB CLIENT ID와 혼용하고 있어서 하나로 통일시켰습니다.
Closes #
=> GOOGLE CLIENT ID 문제

app/dao/insight_article_dao.py, app/dao/interest_dao.py, app/dao/message_dao.py, app/dao/report_dao.py, app/dao/schedule_dao.py, app/langgraph/agent/nodes/summarize_node.py, app/langgraph/insight/nodes/insight_generator.py, app/langgraph/insight/nodes/relation_analyzer.py, app/langgraph/insight/nodes/title_tags_generator.py, app/langgraph/insight/nodes/tts_script_generator.py, app/services/interest_service.py, app/services/message_service.py, app/services/reports/daily/generate_daily_report.py, app/services/reports/daily/get_daily_report.py, app/services/reports/monthly/generate_monthly_report.py, app/services/reports/monthly/get_monthly_report.py, app/services/reports/report_service.py, app/services/reports/summarize_report.py, app/services/reports/weekly/generate_weekly_report.py, app/services/reports/weekly/get_weekly_report.py, app/services/reports/weekly/summarize_weekly_report.py, app/services/schedule_service.py, app/services/session_service.py, app/services/user_service.py, app/utils/openai_client.py, tests/test_dao/test_interest_dao.py, tests/test_dao/test_message_dao.py, tests/test_dao/test_report_dao.py
어제 졸려서 못 본 부분이 있어서 그 부분 수정 + todo로 박아두었던 get_openai_client() 함수 사용에 관해서 내장화 및 get_completion과 get_embedding 안에서 호출하는 것으로 수정해서 해당 두개 함수에 messages만 입력하면 사용할 수 있습니다!
- 
Closes #
=> Refactor/debug 추가 리팩토링

app/services/message_service.py
=> 🐛 bug: 긴급 message 오류 수정

app/routes/session.py
This reverts commit c48948c94494e807693a4804b838f34dbd249e3e.
thread 처리를 되돌립니다.
- 
Closes #
=> Revert "🐛 Fix session close error"

app/__init__.py, app/dao/briefing_dao.py, app/routes/briefing.py, app/routes/debug/briefing.py, app/routes/report.py, app/schemas/briefing_schema.py, app/services/briefing_service.py
프론트엔드에서 요구할 브리핑 text, script 관련 get 함수 구현 PR입니다.
- 브리핑 테이블 script 컬럼 관련 추가하였습니다.
- 실제 서비스에서 사용할 API를 구현하였습니다.
Closes #
=> 브리핑 API 작업

app/__init__.py, app/routes/schedule.py
유지관리의 편의성을 위해 debug/schedule을 schedule로 복제하였습니다.
완전히 동일하게 복제하였습니다. 추후 필요없는 곳 있을 시 부분적으로 정리해도 무방합니다.
- schedule api 추가
- routing
- 그 외 변경사항 없습니다.
Closes #
=> ✨ Add Schedule API & Routing

app/services/auto_task_service.py
auto task 남은 시간 추가 때문에 고장난 걸 고치는 PR
- 처리 방식 수정
Closes #
=> 🐛 Fix remaining time for auto task

app/routes/session.py
session close에서 해줘야 하는 작업들이 모두 비동기로 수행됩니다.
- 관심사 추출이 비동기로 수행됩니다.
- 대화후처리 랭그래프가 비동기로 수행됩니다.
- 유저 메모리 업데이트가 비동기로 수행됩니다.
Closes #
=> ⚡️ Introduce async for session close

app/services/reports/weekly/generate_weekly_report.py
기존의 주차 계산 방식이 잘못되어 있어서 수정했습니다
오늘 6월 9일 기준으로 2주차여야 하는데 3주차로 계산되고 있었음.
- 
Closes #
=> 📆 fix: 주차 계산 방식 수정

app/langgraph/agent/nodes/call_model.py, app/utils/prompt/agent_prompt.py
오늘은 2025년 6월 9일입니다
2023년이 아니에요.
- 정확한 날짜 정보를 llm이 가지고 있도록 수정했습니다.
Closes #
=> 🪡 add: 오늘 날짜 불러오기

app/langgraph/background/nodes/dequeue_ready_step.py, app/langgraph/background/nodes/fetch_next_task.py, app/langgraph/background/nodes/run_tool.py, app/utils/auto_task_utils.py
Add auto_task DB start_at 등록
- 백그라운드 랭그래프에서 작업 시작 시 start_at 등록되도록 코드 추가
Closes #
=> ➕ Add auto_task DB start_at 등록

app/langgraph/background/bg_state.py, app/langgraph/background/nodes/dequeue_ready_step.py, app/langgraph/background/nodes/evaluate_step.py, app/langgraph/background/nodes/run_tool.py
current_step 컬럼에 진행 사항 list 로 저장되도록 코드 수정
- text -> list 로 변경
Closes #
=> ⬆️ Update current_step list 로 저장

app/routes/debug/background.py, app/routes/session.py, app/utils/auto_task_utils.py
세션 종료 시 자동 업무 백그라운드 실행되도록 코드 추가
Closes #
=> ✨ Introduce session-close route run background
